/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.fengjr.api;

public final class R {
	public static final class raw {
		public static final int fengjr = 0x7f050000;
	}
	public static final class string {
		public static final int UMS_URL = 0x7f06001a;
		public static final int api_apk = 0x7f060050;
		public static final int api_apk_package_local = 0x7f060051;
		public static final int api_banners = 0x7f06001f;
		public static final int api_bindcard = 0x7f060043;
		public static final int api_corporation = 0x7f060026;
		public static final int api_favorite_count = 0x7f060037;
		public static final int api_funds = 0x7f060047;
		public static final int api_get_credit_images = 0x7f06004f;
		public static final int api_invests = 0x7f060048;
		public static final int api_isfavorite = 0x7f060038;
		public static final int api_loan = 0x7f060025;
		public static final int api_loan_detail = 0x7f060028;
		public static final int api_loan_filter = 0x7f060023;
		public static final int api_loan_invests = 0x7f060029;
		public static final int api_loan_proofs = 0x7f060031;
		public static final int api_loan_user = 0x7f060027;
		public static final int api_loans = 0x7f060022;
		public static final int api_loans_2 = 0x7f06004a;
		public static final int api_loans_purpose = 0x7f060024;
		public static final int api_loans_scheduled = 0x7f06004b;
		public static final int api_loans_summary = 0x7f060020;
		public static final int api_loans_summary_purpose = 0x7f060021;
		public static final int api_login = 0x7f06001b;
		public static final int api_mark_favorite = 0x7f060035;
		public static final int api_msg_count = 0x7f06004e;
		public static final int api_msg_read = 0x7f06004c;
		public static final int api_my_authenticates = 0x7f06003d;
		public static final int api_my_fund = 0x7f06003c;
		public static final int api_my_fund_account = 0x7f06003b;
		public static final int api_my_fund_records = 0x7f06003e;
		public static final int api_my_invests = 0x7f060039;
		public static final int api_my_invests_purpose = 0x7f06003a;
		public static final int api_my_project_favorites = 0x7f060033;
		public static final int api_my_project_investinfos = 0x7f060034;
		public static final int api_my_project_invests = 0x7f060032;
		public static final int api_my_statistics = 0x7f06003f;
		public static final int api_notifications = 0x7f06004d;
		public static final int api_payment = 0x7f060044;
		public static final int api_payment_project = 0x7f060045;
		public static final int api_project = 0x7f06002f;
		public static final int api_project_proofs = 0x7f060030;
		public static final int api_projects = 0x7f06002b;
		public static final int api_projects_list = 0x7f06002c;
		public static final int api_projects_summary = 0x7f06002a;
		public static final int api_public_key = 0x7f06001c;
		public static final int api_register = 0x7f06001d;
		public static final int api_reward_address = 0x7f060046;
		public static final int api_reward_relate = 0x7f06002e;
		public static final int api_rewards = 0x7f06002d;
		public static final int api_session = 0x7f060042;
		public static final int api_sms_captcha = 0x7f06001e;
		public static final int api_stockdata = 0x7f060049;
		public static final int api_ump = 0x7f060040;
		public static final int api_unmark_favorite = 0x7f060036;
		public static final int api_v2_agreement = 0x7f06005b;
		public static final int api_v2_bind_agreement = 0x7f06005a;
		public static final int api_v2_check_login_name = 0x7f06005e;
		public static final int api_v2_feedback = 0x7f060053;
		public static final int api_v2_islike = 0x7f060056;
		public static final int api_v2_likecount = 0x7f060057;
		public static final int api_v2_marklike = 0x7f060054;
		public static final int api_v2_payment_info = 0x7f06005d;
		public static final int api_v2_project_list_with_ordianl = 0x7f06005f;
		public static final int api_v2_project_tender_nopwd = 0x7f060059;
		public static final int api_v2_shipping_address = 0x7f060052;
		public static final int api_v2_tender_nopwd = 0x7f060058;
		public static final int api_v2_unmarklike = 0x7f060055;
		public static final int api_v2_upayment_register = 0x7f06005c;
		public static final int api_version = 0x7f060041;
		public static final int base = 0x7f060015;
		public static final int base_beta = 0x7f060018;
		public static final int base_cc = 0x7f060019;
		public static final int base_prod = 0x7f060016;
		public static final int base_test = 0x7f060017;
		
		public static final int api_apply_experience =0x7f070018;
		public static final int api_v2_media = 0x7f070019;
		public static final int api_v2_loan_template = 0x7f070020;
		public static final int api_v2_invest_contract = 0x7f070021;
		public static final int api_reward_confirm = 0x7f070022;
		public static final int api_v2_return_money_query = 0x7f070023;
		public static final int api_v2_repayment_plan = 0x7f070024;
		public static final int api_reward_contract = 0x7f070025;
		public static final int api_v2_publications = 0x7f070026;
		public static final int api_v2_webnotification = 0x7f070027;
		public static final int api_v2_new_webnotification = 0x7f070028;
		public static final int api_v2_invest_contract_credit_assign = 0x7f070029;
		public static final int api_v2_invest_contract_credit_assign_already = 0x7f070030;
		public static final int api_transfer_repay_list = 0x7f070031;
		public static final int api_loan_tranfer_filter = 0x7f070032;
		public static final int api_transfer_loan_detail = 0x7f070033;
		public static final int api_transfer_buy_expect = 0x7f070034;
		public static final int api_transfer_buy = 0x7f070035;
		public static final int api_repayment_plan_creditassign = 0x7f070036;
		public static final int api_v2_invest_record_hold = 0x7f070037;
		public static final int api_v2_invest_record_assigned_already = 0x7f070038;
		public static final int api_v2_markall = 0x7f070039;
		public static final int api_credit_assign_send_captcha = 0x7f070040;
		public static final int api_credit_assign_expect = 0x7f070041;
		public static final int api_create_credit_assign = 0x7f070042;
		
	}
}